### ISSUE TITLE
Pulling backend (docker.io/deso-protocol/backend:stable)

### ISSUE THREAD

**Issue by SmartMeshFoundation** [deso-protocol/run#81]
Pulling backend (docker.io/deso-protocol/backend:stable)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

**Comment by tijno** [comment]
Yeah looks like they changed the image URLs @SmartMeshFoundation but did not get this right, and also make them public.

You can make the following amendments to l5 and l19

Replace `docker.io/deso-protocol/` with `docker.io/bitclout/` - until errors been corrected.

https://github.com/deso-protocol/run/blob/main/docker-compose.dev.yml#L5

https://github.com/deso-protocol/run/blob/main/docker-compose.dev.yml#L19

@maebeam @lazynina the image URLs in compose config is not correct. Two issues I can see:

1. Hub org name is `desoprotocol` not `deso-protocol` eg https://hub.docker.com/u/desoprotocol
2. backend and frontend images are either not created within that ORG or still private

**Comment by maebeam** [comment]
Thanks for the report, I will fix this today

**Comment by maebeam** [comment]
This should be fixed now. Thanks all!
