### ISSUE TITLE
http://deso.run is not available. 

### ISSUE THREAD

**Issue by cryptoescrowsystem** [deso-protocol/run#90]
Unable to connect

Firefox can’t establish a connection to the server at deso.run.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Tor Browser is permitted to access the Web.

**Comment by tijno** [comment]
its supposed to resolve to 127.0.0.1

seems to in most places 

https://www.whatsmydns.net/#A/deso.run

maybe issue with your dns provider ?

**Comment by cryptoescrowsystem** [comment]
Same issue in different locations.... Europe, Asia, USA, South America... Can not be an issue with one DNS Provider.

**Comment by tijno** [comment]
im not seeing that - all regions apart from mexico return localhost  ip for me

but ... i dont use deso.run so cant test

**Comment by cryptoescrowsystem** [comment]
What other options do you suggest in order to run the DeSo Node?

**Comment by tijno** [comment]
put deso.run in your local hosts file and point it to 127.0.0.1

**Comment by maebeam** [comment]
This domain resolves correctly everywhere across a variety of DNS providers for me. If you run `dig deso.run` on your computer what do you see?

**Comment by cryptoescrowsystem** [comment]
> This domain resolves correctly everywhere across a variety of DNS providers for me. If you run `dig deso.run` on your computer what do you see?

Thank you for your support and guidance.

**Comment by cryptoescrowsystem** [comment]
> put deso.run in your local hosts file and point it to 127.0.0.1

Thank you so much for helping us.

**Comment by cryptoescrowsystem** [comment]
The "Admin" button - 

> This domain resolves correctly everywhere across a variety of DNS providers for me. If you run `dig deso.run` on your computer what do you see?

It says "Wrong spelling or incorrect demand"
