### ISSUE TITLE
I can not send trx and  has error "because peer is in read-only: true"

### ISSUE THREAD

**Issue by fiser321** [deso-protocol/run#92]
![image](https://user-images.githubusercontent.com/8924920/147801431-e8962a2f-67b3-4606-a1a9-6b04938df80d.png)

![image](https://user-images.githubusercontent.com/8924920/147801397-2d97d084-5b56-417f-896b-cdb2bb8ef454.png)

how solve this question ? please help me

**Comment by tijno** [comment]
have you tried readonly=false and restarting your node

**Comment by fiser321** [comment]
I alse see this error "because peer is in read-only: true" please help me




在 2021-12-31 15:23:51，"tijno" ***@***.***> 写道：

have you tried readonly=false and restarting your node

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by maebeam** [comment]
I pushed a fix for this, please try it

**Comment by fiser321** [comment]
thank you  I already solve this question  I try restart backend ,but env has no change   finaly I remove  container of backend then it is ok
